# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.1

EAPI=8

CRATES="
	aho-corasick-0.7.18
	ansi_term-0.12.1
	anyhow-1.0.53
	assert_cmd-1.0.8
	async-trait-0.1.52
	atty-0.2.14
	autocfg-1.1.0
	bitflags-1.3.2
	block-buffer-0.7.3
	block-padding-0.1.5
	bstr-0.2.17
	byte-tools-0.3.1
	byteorder-1.4.3
	cc-1.0.72
	cfg-if-1.0.0
	chrono-0.4.19
	chrono-tz-0.6.1
	chrono-tz-build-0.0.2
	clap-3.1.0
	clap_complete-3.0.6
	clap_derive-3.1.0
	cmd_lib-1.3.0
	cmd_lib_macros-1.3.0
	colored-2.0.0
	config-0.12.0
	conventional_commit_parser-0.9.4
	crossbeam-utils-0.8.7
	ctor-0.1.21
	deunicode-0.4.3
	diff-0.1.12
	difference-2.0.0
	difflib-0.4.0
	digest-0.8.1
	doc-comment-0.3.3
	edit-0.1.3
	either-1.6.1
	faccess-0.2.3
	fake-simd-0.1.2
	fastrand-1.7.0
	float-cmp-0.8.0
	fnv-1.0.7
	form_urlencoded-1.0.1
	fuchsia-cprng-0.1.1
	generic-array-0.12.4
	getrandom-0.1.16
	getrandom-0.2.4
	git2-0.13.25
	globset-0.4.8
	globwalk-0.8.1
	hashbrown-0.11.2
	heck-0.4.0
	hermit-abi-0.1.19
	humansize-1.1.1
	idna-0.2.3
	ignore-0.4.18
	indexmap-1.8.0
	indoc-1.0.3
	instant-0.1.12
	itertools-0.10.3
	itoa-1.0.1
	jobserver-0.1.24
	lazy_static-1.4.0
	libc-0.2.117
	libgit2-sys-0.12.26+1.3.0
	libz-sys-1.1.3
	log-0.4.16
	maplit-1.0.2
	matches-0.1.9
	memchr-2.4.1
	minimal-lexical-0.2.1
	nom-7.1.0
	normalize-line-endings-0.3.0
	num-0.1.42
	num-bigint-0.1.44
	num-complex-0.1.43
	num-integer-0.1.44
	num-iter-0.1.42
	num-rational-0.1.42
	num-traits-0.2.14
	opaque-debug-0.2.3
	os_pipe-0.9.2
	os_str_bytes-6.0.0
	output_vt100-0.1.2
	parse-zoneinfo-0.3.0
	pathdiff-0.2.1
	percent-encoding-2.1.0
	pest-2.1.3
	pest_derive-2.1.0
	pest_generator-2.1.3
	pest_meta-2.1.3
	phf-0.10.1
	phf_codegen-0.10.0
	phf_generator-0.10.0
	phf_shared-0.10.0
	pkg-config-0.3.24
	ppv-lite86-0.2.16
	predicates-1.0.8
	predicates-2.1.1
	predicates-core-1.0.3
	predicates-tree-1.0.5
	pretty_assertions-1.1.0
	proc-macro-error-1.0.4
	proc-macro-error-attr-1.0.4
	proc-macro2-1.0.36
	quick-error-1.2.3
	quote-1.0.15
	rand-0.4.6
	rand-0.7.3
	rand-0.8.4
	rand_chacha-0.2.2
	rand_chacha-0.3.1
	rand_core-0.3.1
	rand_core-0.4.2
	rand_core-0.5.1
	rand_core-0.6.3
	rand_hc-0.2.0
	rand_hc-0.3.1
	rdrand-0.4.0
	redox_syscall-0.2.10
	regex-1.5.4
	regex-automata-0.1.10
	regex-syntax-0.6.25
	remove_dir_all-0.5.3
	rustc-serialize-0.3.24
	rusty-forkfork-0.4.0
	ryu-1.0.9
	same-file-1.0.6
	sealed_test-0.2.0
	sealed_test_derive-0.1.0
	semver-1.0.5
	serde-1.0.136
	serde_derive-1.0.136
	serde_json-1.0.79
	sha-1-0.8.2
	shell-words-1.1.0
	siphasher-0.3.9
	slug-0.1.4
	speculoos-0.8.0
	stderrlog-0.5.1
	strsim-0.10.0
	syn-1.0.86
	tempfile-3.3.0
	tera-1.15.0
	termcolor-1.1.2
	termtree-0.2.4
	textwrap-0.14.2
	thread_local-1.0.1
	time-0.1.44
	tinyvec-1.5.1
	tinyvec_macros-0.1.0
	toml-0.5.8
	typenum-1.15.0
	ucd-trie-0.1.3
	uncased-0.9.6
	unic-char-property-0.9.0
	unic-char-range-0.9.0
	unic-common-0.9.0
	unic-segment-0.9.0
	unic-ucd-segment-0.9.0
	unic-ucd-version-0.9.0
	unicode-bidi-0.3.7
	unicode-normalization-0.1.19
	unicode-xid-0.2.2
	unindent-0.1.7
	url-2.2.2
	vcpkg-0.2.15
	version_check-0.9.4
	wait-timeout-0.2.0
	walkdir-2.3.2
	wasi-0.9.0+wasi-snapshot-preview1
	wasi-0.10.0+wasi-snapshot-preview1
	which-4.2.4
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Cocogitto is a set of cli tools for the conventional commit and semver specifications."
HOMEPAGE="https://github.com/${PN}/${PN}"

if [[ "${PV}" == *9999* ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/${PN}/${PN}.git"
else
	SRC_URI="https://github.com/${PN}/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
		$(cargo_crate_uris)"
	KEYWORDS="~amd64 ~x86"
fi

RESTRICT="mirror"
LICENSE="Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 CC0-1.0 ISC MIT MPL-2.0 Unlicense ZLIB"
SLOT="0"
IUSE="bash-completion zsh-completion fish-completion"
RDEPEND="
	bash-completion? ( app-shells/bash-completion )
"

src_unpack() {
	if [[ "${PV}" == *9999* ]]; then
		git-r3_src_unpack
		cargo_live_src_unpack
	else
		cargo_src_unpack
	fi
}

src_install() {
	default
	cargo_src_install

	install_completion() {
		./target/$(usex debug debug release)/cog completion "$1" > "$1-completion"
		insinto "$2"
		newins "$1-completion" "$3"
	}

	# Install shell completions if enabled
	use bash-completion && install_completion "bash" "/usr/share/bash-completion/completions" "cog"
	use zsh-completion && install_completion "zsh" "/usr/share/zsh/site-functions" "_cog"
	use fish-completion && install_completion "fish" "/usr/share/fish/completions" "cog.fish"
}
