# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

LUA_COMPAT=( lua5-1 )
RUST_MIN_VER="1.92.0"

inherit lua-single shell-completion cargo

DESCRIPTION="The front-end to your dev env"
HOMEPAGE="https://mise.jdx.dev"
if [[ "${PV}" == *9999* ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/jdx/mise.git"
else
	SRC_URI="https://github.com/jdx/mise/archive/v${PV}.tar.gz -> ${P}.tar.gz
		${CARGO_CRATE_URIS}"
	KEYWORDS="~amd64 ~x86"
fi

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD-2 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 openssl
	Unicode-3.0 ZLIB BZIP2
"
SLOT="0"
IUSE="bash-completion fish-completion zsh-completion man"
DEPEND="
	${LUA_DEPS}
	app-arch/bzip2
	app-arch/zstd
	dev-libs/openssl
	virtual/zlib
"
RDEPEND="
	${DEPEND}
	bash-completion? ( app-shells/bash-completion )
	fish-completion? ( app-shells/fish )
	zsh-completion? ( app-shells/zsh )
"
BDEPEND="
	${DEPEND}
	virtual/pkgconfig
"
REQUIRED_USE="${LUA_REQUIRED_USE}"
RESTRICT="mirror"

src_unpack() {
	if [[ "${PV}" == *9999* ]]; then
		git-r3_src_unpack
		cargo_live_src_unpack
	else
		cargo_src_unpack
	fi
}

src_configure() {
	export ZSTD_SYS_USE_PKG_CONFIG=1
	export OPENSSL_NO_VENDOR=1
	export PKG_CONFIG_ALLOW_CROSS=1

	local myfeatures=(
		native-tls
	)
	cargo_src_configure --no-default-features
}

src_install() {
	cargo_src_install

	if use man; then
		./target/$(usex debug debug release)/mise generate-manpages "${ED}/usr/share/man/man1" || die "Failed to generate man pages"
	fi

	if use man; then
		doman man/man1/mise.1 || die "Failed to install manpage"
	fi

	generate_completion() {
		./target/$(usex debug debug release)/mise completion "${1}" &> "mise.${1}" || die "Failed to generate $1 completion"
		echo "mise.${1}"
	}

	# Disable self-update functionality
	insinto /usr/lib/mise
	doins "${FILESDIR}"/mise-self-update-instructions.toml

	# Enable paranoid mode system-wide
	insinto /etc/mise
	doins "${FILESDIR}"/config.toml

	# Install shell completions if enabled
	if use bash-completion; then
		newzshcomp "$(generate_completion "bash")" mise
	fi

	if use fish-completion; then
		newfishcomp "$(generate_completion "fish")" mise.fish
	fi

	if use zsh-completion; then
		newzshcomp "$(generate_completion "zsh")" _mise
	fi
}
